const express=require('express'),session=require('express-session'),pgSession=require('connect-pg-simple')(session),{Pool}=require('pg'),bcrypt=require('bcryptjs'),path=require('path');
const app=express(),PORT=process.env.PORT||10000,pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(session({store:process.env.DATABASE_URL?new pgSession({pool,tableName:'user_sessions',createTableIfMissing:true}):undefined,secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{maxAge:604800000,httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}}));
async function db(q,p=[]){if(!process.env.DATABASE_URL)throw Error('DATABASE_URL não configurada.');return pool.query(q,p)}
async function init(){if(!process.env.DATABASE_URL){console.warn('DATABASE_URL não configurada.');return}await db(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member',grade INTEGER NOT NULL DEFAULT 4,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await db(`CREATE TABLE IF NOT EXISTS news(id SERIAL PRIMARY KEY,title TEXT NOT NULL,content TEXT NOT NULL,author_id INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`)}
const auth=(req,res,n)=>req.session.user?n():res.status(401).json({error:'Faça login primeiro.'}),admin=(req,res,n)=>req.session.user?.role==='admin'?n():res.status(403).json({error:'Acesso restrito à Era Heian.'});
app.post('/api/register',async(req,res)=>{try{let u=String(req.body.username||'').trim(),p=String(req.body.password||'');if(u.length<3||u.length>30)return res.status(400).json({error:'O usuário deve ter entre 3 e 30 caracteres.'});if(p.length<6)return res.status(400).json({error:'A senha precisa ter pelo menos 6 caracteres.'});let c=await db('SELECT COUNT(*)::int n FROM users'),first=c.rows[0].n===0,h=await bcrypt.hash(p,12);await db('INSERT INTO users(username,password_hash,role,grade,status) VALUES($1,$2,$3,$4,$5)',[u,h,first?'admin':'member',first?1:4,first?'approved':'pending']);res.json({ok:true,message:first?'Conta criada como administrador.':'Cadastro enviado. Aguarde a aprovação da Era Heian.'})}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'Esse usuário já existe.':'Erro ao criar conta.'})}});
app.post('/api/login',async(req,res)=>{try{let u=String(req.body.username||'').trim(),p=String(req.body.password||''),r=await db('SELECT id,username,password_hash,role,grade,status FROM users WHERE username=$1',[u]),x=r.rows[0];if(!x||!(await bcrypt.compare(p,x.password_hash)))return res.status(401).json({error:'Usuário ou senha incorretos.'});if(x.status!=='approved')return res.status(403).json({error:`Seu cadastro está ${x.status==='pending'?'pendente':'rejeitado'}.`});req.session.user={id:x.id,username:x.username,role:x.role,grade:x.grade};res.json({ok:true,user:req.session.user})}catch(e){res.status(500).json({error:'Erro ao entrar.'})}});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));app.get('/api/me',(req,res)=>res.json({user:req.session.user||null}));
app.get('/api/news',async(req,res)=>{try{let r=await db('SELECT n.id,n.title,n.content,n.created_at,u.username author FROM news n LEFT JOIN users u ON u.id=n.author_id ORDER BY n.created_at DESC');res.json(r.rows)}catch(e){res.status(500).json({error:'Não foi possível carregar as notícias.'})}});
app.post('/api/news',admin,async(req,res)=>{try{let t=String(req.body.title||'').trim(),c=String(req.body.content||'').trim();if(!t||!c)return res.status(400).json({error:'Preencha título e conteúdo.'});await db('INSERT INTO news(title,content,author_id) VALUES($1,$2,$3)',[t,c,req.session.user.id]);res.json({ok:true})}catch(e){res.status(500).json({error:'Erro ao publicar.'})}});app.delete('/api/news/:id',admin,async(req,res)=>{try{await db('DELETE FROM news WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({error:'Erro ao excluir.'})}});
app.get('/api/members',auth,async(req,res)=>{try{let r=await db("SELECT id,username,role,grade,status,created_at FROM users WHERE status='approved' ORDER BY role DESC,grade ASC,created_at ASC");res.json(r.rows)}catch(e){res.status(500).json({error:'Erro ao carregar membros.'})}});
app.get('/api/admin/pending',admin,async(req,res)=>{try{let r=await db("SELECT id,username,created_at FROM users WHERE status='pending' ORDER BY created_at ASC");res.json(r.rows)}catch(e){res.status(500).json({error:'Erro ao carregar pendentes.'})}});
app.post('/api/admin/users/:id/decision',admin,async(req,res)=>{try{if(!['approved','rejected'].includes(req.body.decision))return res.status(400).json({error:'Decisão inválida.'});await db('UPDATE users SET status=$1 WHERE id=$2',[req.body.decision,req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({error:'Erro ao atualizar cadastro.'})}});
app.use(express.static(path.join(__dirname,'public')));app.use((req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));init().then(()=>app.listen(PORT,()=>console.log('Portal JJK online na porta '+PORT))).catch(e=>{console.error(e);process.exit(1)});
